[package]
name = "texcreate-local-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
texc-web = "0.1.7"
tokio = {version = "1.0", features = ["full"]}